### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [erskin19/rubyAuth#1]
I think you may have misunderstood this criterion:

> NOT display any links to unauthorized actions to anonymous visitors (such as links to create a new record, edit a record, or delete a record)

I would still like to see a link to the list of comments when not signed in, since anonymous visitors are allowed to visit the `index` and `show` actions. It's just links to the other actions (that users are not authorized to use) that I'd like hidden. Let me know if that makes sense.

**Comment by erskin19** [comment]
This should be fixed.

**Comment by chrisvfritz** [comment]
This is slightly better, but still doesn't meet that criterion. It might be easier to explain in person exactly what's wrong, so let's fix this on Monday.

**Comment by erskin19** [comment]
I think I got it this time, please check it again. I misread the requirement. Sorry for the misunderstanding

**Comment by chrisvfritz** [comment]
Much better! I just see [one more link](https://github.com/erskin19/rubyAuth/blob/master/app/views/commenters/show.html.erb#L18) you missed.

**Comment by erskin19** [comment]
Just pushed that last hidden link

**Comment by chrisvfritz** [comment]
:+1: Looks great!
